export const PLANTS_DB = [
  {
    id: 1,
    name: "Monstera Deliciosa",
    category: "interior",
    price: 29.99,
    light: "media",
    water: "alta",
    pets: "no",
    image: "assets/monstera.png",
    lightDesc: "Luz indirecta",
    waterDesc: "Riego moderado",
    petDesc: "Tóxica para mascotas",
    desc: "Una planta tropical icónica con hermosas hojas recortadas. Perfecta para dar vida a cualquier rincón interior.",
    stock: 8
  },
  {
    id: 2,
    name: "Sansevieria (Planta Serpiente)",
    category: "interior",
    price: 19.99,
    light: "baja",
    water: "baja",
    pets: "no",
    image: "assets/snake_plant.png",
    lightDesc: "Poca luz / Sombra",
    waterDesc: "Poco riego",
    petDesc: "Tóxica para mascotas",
    desc: "Casi indestructible y excelente purificadora de aire. Tolera poca luz y riegos muy distanciados.",
    stock: 1
  },
  {
    id: 3,
    name: "Jardín de Suculentas",
    category: "suculentas",
    price: 34.99,
    light: "alta",
    water: "baja",
    pets: "si",
    image: "assets/succulent_garden.png",
    lightDesc: "Luz directa / Alta",
    waterDesc: "Poco riego",
    petDesc: "Segura para mascotas",
    desc: "Un hermoso arreglo artesanal de suculentas variadas en un cuenco minimalista. Ideal para escritorios soleados.",
    stock: 6
  },
  {
    id: 4,
    name: "Helecho de Boston",
    category: "interior",
    price: 18.99,
    light: "media",
    water: "alta",
    pets: "si",
    image: "assets/monstera.png",
    lightDesc: "Luz media indirecta",
    waterDesc: "Riego frecuente",
    petDesc: "Segura para mascotas",
    desc: "Hojas plumosas y elegantes que cuelgan con gracia. Requiere humedad constante y luz tamizada.",
    stock: 3
  },
  {
    id: 5,
    name: "Cactus de Jade",
    category: "suculentas",
    price: 15.99,
    light: "alta",
    water: "baja",
    pets: "si",
    image: "assets/succulent_garden.png",
    lightDesc: "Luz directa alta",
    waterDesc: "Poco riego",
    petDesc: "Segura para mascotas",
    desc: "Cactus de crecimiento lento con hermosas espinas doradas. Muy resistente y decorativo.",
    stock: 10
  },
  {
    id: 6,
    name: "Romero Aromático",
    category: "exterior",
    price: 12.99,
    light: "alta",
    water: "baja",
    pets: "si",
    image: "assets/snake_plant.png",
    lightDesc: "Sol directo",
    waterDesc: "Poco riego",
    petDesc: "Segura para mascotas",
    desc: "Planta mediterránea super aromática. Perfecta para balcones soleados y para uso culinario.",
    stock: 2
  },
  {
    id: 7,
    name: "Buganvilla de Verano",
    category: "exterior",
    price: 45.99,
    light: "alta",
    water: "alta",
    pets: "no",
    image: "assets/hero_greenhouse.png",
    lightDesc: "Sol directo pleno",
    waterDesc: "Riego regular",
    petDesc: "Tóxica para mascotas",
    desc: "Enredadera espectacular con abundantes flores de color fucsia brillante. Llena de vida  terrazas y patios.",
    stock: 7
  },
  {
    id: 8,
    name: "Palma de Salón (Chamaedorea)",
    category: "interior",
    price: 22.99,
    light: "media",
    water: "alta",
    pets: "si",
    image: "assets/monstera.png",
    lightDesc: "Luz indirecta media",
    waterDesc: "Riego regular",
    petDesc: "Segura para mascotas",
    desc: "Palmera compacta y elegante que tolera condiciones variadas de interior. 100% segura para tus mascotas.",
    stock: 4
  }
];

export const BOT_KNOWLEDGE = {
  riego: "💧 El riego depende de la planta. Las suculentas y plantas desérticas prefieren secarse por completo (riego cada 10-15 días). Plantas tropicales como la Monstera o Helechos necesitan sustrato húmedo pero sin encharcar (aprox. 1 o 2 veces por semana). ¡Toca el sustrato a 3cm de profundidad para comprobar la humedad antes de regar!",
  monstera: "🌿 La Monstera Deliciosa prefiere luz brillante indirecta. Si recibe sol directo se le quemarán las hojas, y si hay poca luz crecerá lento y sin sus hermosos agujeros característicos. Riégala cuando el sustrato se empiece a secar.",
  luz: "☀️ La mayoría de las plantas necesitan luz indirecta. La luz directa fuerte (a través del vidrio de la ventana al mediodía) puede quemar hojas delicadas. Si tu espacio tiene poca luz, te recomiendo la Sansevieria o el Poto.",
  amarilla: "🍂 Las hojas amarillas suelen indicar exceso de agua (riego muy frecuente) o que las raíces se están asfixiando por falta de drenaje. Reduce los riegos y asegúrate de que la maceta drene bien. A veces también puede ser falta de nitrógeno o abono.",
  marron: "🤎 Las puntas marrones o secas en las hojas generalmente se deben a falta de humedad ambiental o riego insuficiente. Puedes pulverizar agua limpia sobre las hojas tropicales o colocar un plato con piedras y agua debajo de la maceta.",
  sombra: "☁️ Para rincones con poca luz, tus mejores aliadas son la Sansevieria (Planta Serpiente), la Zamioculca (Gema de Zanzíbar) y el Poto (Epipremnum). Estas plantas toleran muy bien la penumbra.",
  abono: "🌱 Te recomendamos abonar tus plantas durante la primavera y verano (época de crecimiento activo) cada 15 o 30 días con fertilizante líquido diluido en agua de riego. Evita fertilizar en invierno.",
  mascota: "🐾 Varias plantas son tóxicas para perros y gatos (como Monstera, Potos o Lirios). Te recomendamos elegir plantas Pet-Friendly como la Palma de Salón, Helechos, Calateas o Suculentas si tienes animales curiosos."
};
