import { useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useDemoStore } from '../../app/providers/DemoStore'
import { DemoBanner } from '../../components/feedback/DemoBanner'
import type { PlantCategory } from '../../types/domain'

type AdminTab = 'editorial' | 'inventario' | 'stock' | 'promociones' | 'ventas' | 'pedidos' | 'personal'
const tabs: Array<{ id: AdminTab; label: string }> = [{ id: 'editorial', label: '📝 Editorial' }, { id: 'inventario', label: '📦 Productos' }, { id: 'stock', label: '📈 Inventario' }, { id: 'promociones', label: '🏷 Promociones' }, { id: 'ventas', label: '📊 Ventas' }, { id: 'pedidos', label: '🧾 Pedidos' }, { id: 'personal', label: '👥 Personal' }]

export function AdminPage() {
  const [searchParams] = useSearchParams()
  const initialTab = tabs.some(({ id }) => id === searchParams.get('tab')) ? searchParams.get('tab') as AdminTab : 'editorial'
  const [tab, setTab] = useState<AdminTab>(initialTab)
  const { plants, orders, editorial, staff, addPlant, setDiscount, restock, setEditorial, toggleStaff } = useDemoStore()
  const [notice, setNotice] = useState('')
  const revenue = orders.reduce((sum, order) => sum + order.total, 0)

  const saveEditorial = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setEditorial({ title: String(data.get('title')), description: String(data.get('description')), announcement: String(data.get('announcement')) }); setNotice('Contenido editorial actualizado localmente.') }
  const createPlant = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addPlant({ name: String(data.get('name')), category: String(data.get('category')) as PlantCategory, price: Number(data.get('price')), light: 'media', water: 'alta', pets: true, image: plants[0].image, lightDesc: 'Luz indirecta', waterDesc: 'Riego moderado', petDesc: 'Segura para mascotas', description: String(data.get('description')), stock: Number(data.get('stock')) }); event.currentTarget.reset(); setNotice('Producto de demostración agregado localmente.') }
  const savePromotion = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setDiscount(Number(data.get('plantId')), Number(data.get('discount'))); setNotice('Promoción de demostración actualizada.') }

  return <main className="internal-page"><div className="dashboard-panel open embedded"><div className="dashboard-header"><div><h2>Panel Vivero Dulcinea</h2><DemoBanner compact /></div><div className="dashboard-header-actions"><span className="role-badge-db admin">Demo</span><Link className="logout-btn" to="/login">Salir</Link></div></div><div className="dashboard-body"><aside className="dashboard-sidebar"><nav aria-label="Módulos administrativos"><ul>{tabs.map((item) => <li key={item.id}><button className={`db-nav-item ${tab === item.id ? 'active' : ''}`} onClick={() => { setTab(item.id); setNotice('') }}>{item.label}</button></li>)}</ul></nav></aside><section className="dashboard-content"><p className="form-notice" aria-live="polite">{notice}</p>
    {tab === 'editorial' && <section className="db-tab-content active"><h3>Gestión editorial</h3><p className="demo-copy">Los cambios solo se guardan en este navegador.</p><form className="dashboard-form" onSubmit={saveEditorial}><div className="form-group"><label htmlFor="hero-title">Título principal</label><input id="hero-title" name="title" defaultValue={editorial.title} required /></div><div className="form-group"><label htmlFor="hero-description">Descripción</label><textarea id="hero-description" name="description" defaultValue={editorial.description} required /></div><div className="form-group"><label htmlFor="announcement">Anuncio</label><input id="announcement" name="announcement" defaultValue={editorial.announcement} required /></div><button className="submit-db-btn">Guardar cambios demo</button></form></section>}
    {tab === 'inventario' && <section className="db-tab-content active"><h3>Agregar producto</h3><form className="dashboard-form" onSubmit={createPlant}><div className="form-row"><div className="form-group"><label htmlFor="plant-name">Nombre</label><input id="plant-name" name="name" required /></div><div className="form-group"><label htmlFor="plant-category">Categoría</label><select id="plant-category" name="category"><option value="interior">Interior</option><option value="exterior">Exterior</option><option value="suculentas">Suculentas</option></select></div></div><div className="form-row"><div className="form-group"><label htmlFor="plant-price">Precio</label><input id="plant-price" name="price" type="number" min="0.1" step="0.01" required /></div><div className="form-group"><label htmlFor="plant-stock">Existencias</label><input id="plant-stock" name="stock" type="number" min="0" required /></div></div><div className="form-group"><label htmlFor="plant-description">Descripción</label><textarea id="plant-description" name="description" required /></div><button className="submit-db-btn">Agregar producto demo</button></form></section>}
    {tab === 'stock' && <section className="db-tab-content active"><h3>Control de inventario</h3><div className="db-stock-grid">{plants.map((plant) => <article key={plant.id} className={`stock-card ${plant.stock <= 1 ? 'critical' : plant.stock <= 4 ? 'low' : 'adequate'}`}><div className="stock-card-image-container"><img src={plant.image} alt={plant.name} className="stock-card-img-large" /><span className="stock-badge-floating">{plant.stock <= 1 ? '🔴 Crítico' : plant.stock <= 4 ? '🟡 Bajo' : '🟢 Adecuado'}</span></div><div className="stock-card-body"><h4>{plant.name}</h4><p>{plant.stock} unidades · Datos de demostración</p><div className="stock-action-group"><button className="stock-btn" onClick={() => restock(plant.id, 5)}>+5 u.</button><button className="stock-btn" onClick={() => restock(plant.id, 10)}>+10 u.</button></div></div></article>)}</div></section>}
    {tab === 'promociones' && <section className="db-tab-content active"><h3>Promociones</h3><form className="dashboard-form" onSubmit={savePromotion}><div className="form-row"><div className="form-group"><label htmlFor="promo-plant">Producto</label><select id="promo-plant" name="plantId">{plants.map((plant) => <option value={plant.id} key={plant.id}>{plant.name}</option>)}</select></div><div className="form-group"><label htmlFor="promo-discount">Descuento (%)</label><input id="promo-discount" name="discount" type="number" min="0" max="90" required /></div></div><button className="submit-db-btn">Aplicar promoción demo</button></form><DataTable headings={['Producto', 'Precio', 'Descuento']} rows={plants.filter(({ discount }) => discount > 0).map((plant) => [plant.name, `$${plant.price.toFixed(2)}`, `${plant.discount}%`])} /></section>}
    {tab === 'ventas' && <section className="db-tab-content active"><h3>Resumen de ventas</h3><DemoBanner compact /><div className="stats-grid"><Stat label="Ingresos demo" value={`$${revenue.toFixed(2)}`} /><Stat label="Pedidos demo" value={String(orders.length)} /><Stat label="Ticket promedio demo" value={`$${orders.length ? (revenue / orders.length).toFixed(2) : '0.00'}`} /></div></section>}
    {tab === 'pedidos' && <section className="db-tab-content active"><h3>Pedidos</h3><p className="demo-copy">Datos de demostración guardados localmente.</p><DataTable headings={['Pedido', 'Fecha', 'Artículos', 'Total', 'Estado']} rows={orders.map((order) => [order.id, order.createdAt, order.items.map((item) => `${item.name} ×${item.quantity}`).join(', '), `$${order.total.toFixed(2)}`, order.status])} /></section>}
    {tab === 'personal' && <section className="db-tab-content active"><h3>Personal</h3><p className="demo-copy">Datos de demostración.</p><div className="table-responsive"><table className="db-table"><thead><tr><th>Nombre</th><th>Especialidad</th><th>Turno</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{staff.map((member) => <tr key={member.id}><td>{member.name}</td><td>{member.specialty}</td><td>{member.shift}</td><td>{member.active ? 'Activo (demo)' : 'Inactivo (demo)'}</td><td><button className="staff-action-btn" onClick={() => toggleStaff(member.id)}>Alternar turno</button></td></tr>)}</tbody></table></div></section>}
  </section></div></div></main>
}

function Stat({ label, value }: { label: string; value: string }) { return <article className="stat-card"><span className="stat-icon">●</span><div><h4>{label}</h4><p>{value}</p></div></article> }
function DataTable({ headings, rows }: { headings: string[]; rows: string[][] }) { return <div className="table-responsive"><table className="db-table"><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, rowIndex) => <tr key={`${row[0]}-${rowIndex}`}>{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`}>{cell}</td>)}</tr>) : <tr><td colSpan={headings.length}>Sin datos de demostración todavía.</td></tr>}</tbody></table></div> }
